#HikariCP 데이터 소스(DataSource)
spring:
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://52.14.36.21:3306/im_db?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
      username: im_user
      password: cloth
      connection-test-query: SELECT NOW() FROM dual
  # 프로필 설정
  profiles:
    active: local
  output:
    ansi:
      enabled: always
#mybatis 설정
mybatis:
  configuration:
    map-underscore-to-camel-case: true #스네이크 형식으로 변경해줌? VO를 안써서 안쓸듯? <-?

interceptor:
  exclude: /js/**, /fonts/**, /css/**, /plugin/**, /file/**